// ISO alpha-2 lists for region-scoped rules. Extend as the KB grows.
export const REGIONS: Record<string, string[]> = {
  schengen: [
    'AT',
    'BE',
    'HR',
    'CZ',
    'DK',
    'EE',
    'FI',
    'FR',
    'DE',
    'GR',
    'HU',
    'IS',
    'IT',
    'LV',
    'LI',
    'LT',
    'LU',
    'MT',
    'NL',
    'NO',
    'PL',
    'PT',
    'SK',
    'SI',
    'ES',
    'SE',
    'CH',
  ],
  yellow_fever: ['BR', 'CO', 'PE', 'BO', 'CD', 'AO', 'GH', 'KE', 'UG', 'NG'],
  asia_6mo: ['TH', 'VN', 'ID', 'SG', 'MY', 'PH', 'CN'],
};
