/**
 * Runtime contract tests — assert static→runtime promises that unit tests mock away.
 * Generated by the auditing-runtime-contracts skill (Phase 10). These scan SOURCE (never
 * mock the boundary) so they fail in CI instead of in TestFlight/prod.
 *
 * Contracts covered:
 *  1. i18n — every static t('a.b') key used in code resolves in BOTH en + fr.
 *  2. edge functions — every `*_FN = 'name'` / invoke('name') target has a deployed
 *     supabase/functions/<name>/index.ts.
 *  3. ghost sentinel UUID — the deleted-user sentinel is identical across every client
 *     copy AND the migration + delete-account edge function (security-critical constant).
 *  4. onboarding route — the first-run gate's redirect target resolves to a route file.
 *  5. legal URL env — env keys read in @core/env are mapped into app.config extra.
 */
import * as fs from 'fs';
import * as path from 'path';

import en from '@core/i18n/locales/en.json';
import fr from '@core/i18n/locales/fr.json';

const REPO = path.join(__dirname, '../../..');
const SRC = path.join(REPO, 'src');
const CANONICAL_GHOST = 'de1e7e00-0000-4000-8000-000000000000';

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      if (e.name !== 'node_modules' && !e.name.startsWith('.')) out.push(...walk(full));
    } else if (/\.(ts|tsx)$/.test(e.name)) {
      out.push(full);
    }
  }
  return out;
}

const SRC_FILES = walk(SRC).filter((f) => !/\.test\.[tj]sx?$/.test(f) && !f.includes('__tests__'));
const read = (f: string): string => fs.readFileSync(f, 'utf8');
const rel = (f: string): string => path.relative(REPO, f);

function resolveKey(obj: unknown, key: string): unknown {
  return key
    .split('.')
    .reduce<unknown>(
      (a, p) => (a && typeof a === 'object' ? (a as Record<string, unknown>)[p] : undefined),
      obj,
    );
}

describe('runtime contract: i18n keys', () => {
  // Static t('a.b.c') usages only (dynamic/template keys can't be statically verified).
  const KEY_RE = /\bt\(\s*['"]([A-Za-z0-9_]+(?:\.[A-Za-z0-9_]+)+)['"]/g;
  const used = new Map<string, string>();
  for (const f of SRC_FILES) {
    const txt = read(f);
    let m: RegExpExecArray | null;
    while ((m = KEY_RE.exec(txt)) !== null) if (!used.has(m[1])) used.set(m[1], f);
  }

  it('every static t() key resolves in en.json', () => {
    const missing = [...used.entries()]
      .filter(([k]) => typeof resolveKey(en, k) !== 'string')
      .map(([k, f]) => `${k}  (${rel(f)})`);
    expect(missing).toEqual([]);
  });

  it('every static t() key resolves in fr.json', () => {
    const missing = [...used.entries()]
      .filter(([k]) => typeof resolveKey(fr, k) !== 'string')
      .map(([k, f]) => `${k}  (${rel(f)})`);
    expect(missing).toEqual([]);
  });
});

describe('runtime contract: edge functions', () => {
  // `const X_FN = 'name'` declarations + any inline invoke('name').
  const FN_CONST_RE = /\b\w*_FN\s*=\s*['"]([a-z0-9-]+)['"]/g;
  const INVOKE_LIT_RE = /functions\.invoke(?:<[^>]*>)?\(\s*['"]([a-z0-9-]+)['"]/g;
  const names = new Map<string, string>();
  for (const f of SRC_FILES) {
    const txt = read(f);
    for (const re of [FN_CONST_RE, INVOKE_LIT_RE]) {
      let m: RegExpExecArray | null;
      while ((m = re.exec(txt)) !== null) if (!names.has(m[1])) names.set(m[1], f);
    }
  }

  it('found the Phase 10 account edge functions referenced in client code', () => {
    expect([...names.keys()]).toEqual(
      expect.arrayContaining(['delete-account', 'export-account-data']),
    );
  });

  it('every invoked edge-function name has a deployed supabase/functions/<name>/index.ts', () => {
    const missing = [...names.entries()]
      .filter(([n]) => !fs.existsSync(path.join(REPO, 'supabase/functions', n, 'index.ts')))
      .map(([n, f]) => `${n}  (referenced in ${rel(f)})`);
    expect(missing).toEqual([]);
  });
});

describe('runtime contract: ghost sentinel UUID (ADR-010)', () => {
  const UUID_RE =
    /['"]([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})['"]/g;
  const GHOST_HINT = /ghost|sentinel|former\s*travel|de1e7e00/i;

  it('all ghost UUID literals in client code equal the canonical value', () => {
    const found = new Map<string, string>();
    for (const f of SRC_FILES) {
      const txt = read(f);
      if (!GHOST_HINT.test(txt)) continue;
      let m: RegExpExecArray | null;
      while ((m = UUID_RE.exec(txt)) !== null) found.set(m[1].toLowerCase(), f);
    }
    // at least one client file defines it, and every ghost-context UUID is the canonical one
    expect(found.size).toBeGreaterThan(0);
    const divergent = [...found.entries()]
      .filter(([u]) => u !== CANONICAL_GHOST)
      .map(([u, f]) => `${u}  (${rel(f)})`);
    expect(divergent).toEqual([]);
  });

  it('matches the migration SQL literal', () => {
    const mig = read(
      path.join(
        REPO,
        'supabase/migrations/20260606120000_phase10_account_deletion_ghost_purge.sql',
      ),
    );
    expect(mig.includes(CANONICAL_GHOST)).toBe(true);
  });

  it('matches the delete-account edge function literal', () => {
    const fn = read(path.join(REPO, 'supabase/functions/delete-account/index.ts'));
    expect(fn.includes(CANONICAL_GHOST)).toBe(true);
  });
});

describe('runtime contract: onboarding route', () => {
  it('the first-run gate redirect target /(onboarding)/intro resolves to a route file', () => {
    const intro = path.join(SRC, 'app/(onboarding)/intro.tsx');
    expect(fs.existsSync(intro)).toBe(true);
    // and the gate actually points there
    const gate = read(path.join(SRC, 'app/index.tsx'));
    expect(gate.includes('(onboarding)/intro')).toBe(true);
  });
});

describe('runtime contract: legal URL env', () => {
  it('privacy/terms env keys read in @core/env are mapped into app.config extra', () => {
    const env = read(path.join(SRC, 'core/env/index.ts'));
    const cfg = read(path.join(REPO, 'app.config.ts'));
    for (const key of ['EXPO_PUBLIC_PRIVACY_URL', 'EXPO_PUBLIC_TERMS_URL']) {
      if (env.includes(key)) expect(cfg.includes(key)).toBe(true);
    }
  });
});
