-- KB batch 3 (2026-06-06): Caribbean/Central America, more Africa & Asia, non-Schengen Europe, Middle East.
-- DRAFTS pending human source-checking (ADR-1): rows default to not-approved-for-display and are NOT
-- surfaced to users until a human checks each against the official sources below.
-- last_verified = authoring date (2026-06-06), not a human check date. No new region tokens (rows only).
INSERT INTO public.country_requirements
  (id, destination_country, destination_regions, requirement_type, applies_to_passport_countries,
   trip_duration_max_days, trip_purpose, severity, i18n_key, action_url,
   estimated_processing_days, estimated_cost_usd, followup_lead_times, last_verified, source_urls)
VALUES
  ('dominican_republic_eticket','DO','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','good_to_know',
   'smartReminders.kb.dominican_republic_eticket','https://eticket.migracion.gob.do/',
   NULL,NULL,'{14}','2026-06-06','{https://eticket.migracion.gob.do/}'),
  ('jamaica_visa_free','JM','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.jamaica_visa_free','https://www.pica.gov.jm/',
   NULL,NULL,'{14}','2026-06-06','{https://www.pica.gov.jm/}'),
  ('panama_visa_free','PA','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.panama_visa_free','https://www.migracion.gob.pa/',
   NULL,NULL,'{14}','2026-06-06','{https://www.migracion.gob.pa/}'),
  ('nigeria_visa','NG','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','mandatory',
   'smartReminders.kb.nigeria_visa','https://immigration.gov.ng/',
   14,170,'{60,30}','2026-06-06','{https://immigration.gov.ng/}'),
  ('ghana_visa','GH','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','mandatory',
   'smartReminders.kb.ghana_visa','https://www.ghanaimmigration.org/',
   15,60,'{60,30}','2026-06-06','{https://www.ghanaimmigration.org/}'),
  ('senegal_visa_free','SN','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.senegal_visa_free','https://www.diplomatie.gouv.sn/',
   NULL,NULL,'{14}','2026-06-06','{https://www.diplomatie.gouv.sn/}'),
  ('myanmar_evisa','MM','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',28,'{tourism}','mandatory',
   'smartReminders.kb.myanmar_evisa','https://evisa.moip.gov.mm/',
   3,50,'{30,14}','2026-06-06','{https://evisa.moip.gov.mm/}'),
  ('bangladesh_voa','BD','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','strongly_recommended',
   'smartReminders.kb.bangladesh_voa','https://www.visa.gov.bd/',
   1,51,'{14}','2026-06-06','{https://www.visa.gov.bd/}'),
  ('maldives_visa_free','MV','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','good_to_know',
   'smartReminders.kb.maldives_visa_free','https://imuga.immigration.gov.mv/',
   NULL,NULL,'{14}','2026-06-06','{https://imuga.immigration.gov.mv/}'),
  ('laos_evisa','LA','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','strongly_recommended',
   'smartReminders.kb.laos_evisa','https://laoevisa.gov.la/',
   3,50,'{30,14}','2026-06-06','{https://laoevisa.gov.la/}'),
  ('mongolia_visa_free','MN','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','good_to_know',
   'smartReminders.kb.mongolia_visa_free','https://immigration.gov.mn/',
   NULL,NULL,'{14}','2026-06-06','{https://immigration.gov.mn/}'),
  ('ecuador_visa_free','EC','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.ecuador_visa_free','https://www.cancilleria.gob.ec/',
   NULL,NULL,'{14}','2026-06-06','{https://www.cancilleria.gob.ec/}'),
  ('uruguay_visa_free','UY','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.uruguay_visa_free','https://www.gub.uy/ministerio-interior/',
   NULL,NULL,'{14}','2026-06-06','{https://www.gub.uy/ministerio-interior/}'),
  ('ireland_visa_free','IE','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','good_to_know',
   'smartReminders.kb.ireland_visa_free','https://www.irishimmigration.ie/',
   NULL,NULL,'{14}','2026-06-06','{https://www.irishimmigration.ie/}'),
  ('georgia_visa_free','GE','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',180,'{tourism,business}','good_to_know',
   'smartReminders.kb.georgia_visa_free','https://www.geoconsul.gov.ge/',
   NULL,NULL,'{14}','2026-06-06','{https://www.geoconsul.gov.ge/}'),
  ('jordan_visa','JO','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','recommended',
   'smartReminders.kb.jordan_visa','https://www.visitjordan.com/',
   NULL,56,'{30,14}','2026-06-06','{https://www.visitjordan.com/}'),
  ('bahrain_evisa','BH','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','recommended',
   'smartReminders.kb.bahrain_evisa','https://www.evisa.gov.bh/',
   3,29,'{30,14}','2026-06-06','{https://www.evisa.gov.bh/}'),
  ('taiwan_visa_free','TW','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','good_to_know',
   'smartReminders.kb.taiwan_visa_free','https://www.boca.gov.tw/',
   NULL,NULL,'{14}','2026-06-06','{https://www.boca.gov.tw/}')
ON CONFLICT (id) DO NOTHING;
