-- KB batch 2 (2026-06-06): next-tier high-traffic destinations (SE-Asia, Gulf, LatAm, Africa, US B1/B2).
-- DRAFTS pending human source-checking (ADR-1): rows default to not-approved-for-display and are NOT
-- surfaced to users until a human checks each against the official sources below.
-- last_verified = authoring date (2026-06-06), not a human check date.
INSERT INTO public.country_requirements
  (id, destination_country, destination_regions, requirement_type, applies_to_passport_countries,
   trip_duration_max_days, trip_purpose, severity, i18n_key, action_url,
   estimated_processing_days, estimated_cost_usd, followup_lead_times, last_verified, source_urls)
VALUES
  ('singapore_visa_free','SG','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','good_to_know',
   'smartReminders.kb.singapore_visa_free','https://www.ica.gov.sg/enter-transit-depart/entering-singapore/sg-arrival-card',
   NULL,NULL,'{14}','2026-06-06','{https://www.ica.gov.sg/}'),
  ('malaysia_visa_free','MY','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism,business}','good_to_know',
   'smartReminders.kb.malaysia_visa_free','https://imigresen-online.imi.gov.my/mdac/main',
   NULL,NULL,'{14}','2026-06-06','{https://imigresen-online.imi.gov.my/mdac/main}'),
  ('philippines_visa_free','PH','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','good_to_know',
   'smartReminders.kb.philippines_visa_free','https://etravel.gov.ph/',
   NULL,NULL,'{14}','2026-06-06','{https://etravel.gov.ph/}'),
  ('sri_lanka_eta','LK','{}','eta','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','mandatory',
   'smartReminders.kb.sri_lanka_eta','https://eta.gov.lk/',
   3,50,'{30,14}','2026-06-06','{https://eta.gov.lk/}'),
  ('cambodia_evisa','KH','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','strongly_recommended',
   'smartReminders.kb.cambodia_evisa','https://www.evisa.gov.kh/',
   3,36,'{30,14}','2026-06-06','{https://www.evisa.gov.kh/}'),
  ('nepal_voa','NP','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','strongly_recommended',
   'smartReminders.kb.nepal_voa','https://www.immigration.gov.np/',
   1,50,'{14}','2026-06-06','{https://www.immigration.gov.np/}'),
  ('qatar_visa_free','QA','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism,business}','good_to_know',
   'smartReminders.kb.qatar_visa_free','https://www.visitqatar.com/intl/en/plan/visas-and-travel',
   NULL,NULL,'{14}','2026-06-06','{https://hukoomi.gov.qa/}'),
  ('saudi_evisa','SA','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','mandatory',
   'smartReminders.kb.saudi_evisa','https://visa.visitsaudi.com/',
   2,140,'{30,14}','2026-06-06','{https://visa.visitsaudi.com/}'),
  ('oman_evisa','OM','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','recommended',
   'smartReminders.kb.oman_evisa','https://evisa.rop.gov.om/',
   3,52,'{30,14}','2026-06-06','{https://evisa.rop.gov.om/}'),
  ('peru_visa_free','PE','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.peru_visa_free','https://www.gob.pe/migraciones',
   NULL,NULL,'{14}','2026-06-06','{https://www.gob.pe/migraciones}'),
  ('colombia_visa_free','CO','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.colombia_visa_free','https://www.migracioncolombia.gov.co/',
   NULL,NULL,'{14}','2026-06-06','{https://www.migracioncolombia.gov.co/}'),
  ('chile_visa_free','CL','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.chile_visa_free','https://serviciomigraciones.cl/',
   NULL,NULL,'{14}','2026-06-06','{https://serviciomigraciones.cl/}'),
  ('costa_rica_visa_free','CR','{}','other','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','good_to_know',
   'smartReminders.kb.costa_rica_visa_free','https://www.migracion.go.cr/',
   NULL,NULL,'{14}','2026-06-06','{https://www.migracion.go.cr/}'),
  ('cuba_tourist_card','CU','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','mandatory',
   'smartReminders.kb.cuba_tourist_card','https://misiones.minrex.gob.cu/',
   7,50,'{30,14}','2026-06-06','{https://misiones.minrex.gob.cu/}'),
  ('tanzania_visa','TZ','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',90,'{tourism}','mandatory',
   'smartReminders.kb.tanzania_visa','https://eservices.immigration.go.tz/',
   10,50,'{30,14}','2026-06-06','{https://eservices.immigration.go.tz/}'),
  ('ethiopia_evisa','ET','{}','visa','{FR,DE,US,GB,CA,IT,ES,NL,JP,AU}',30,'{tourism}','mandatory',
   'smartReminders.kb.ethiopia_evisa','https://www.evisa.gov.et/',
   3,82,'{30,14}','2026-06-06','{https://www.evisa.gov.et/}'),
  ('us_b1b2_visa','US','{}','visa','{IN,CN,BR,ZA,NG,PH,VN,ID,TH,RU,EG,MA,KE,DZ}',180,'{tourism,business}','mandatory',
   'smartReminders.kb.us_b1b2_visa','https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html',
   60,185,'{60,30}','2026-06-06','{https://travel.state.gov/content/travel/en/us-visas/tourism-visit/visitor.html}')
ON CONFLICT (id) DO NOTHING;
